#!/bin/bash
# deploy.sh - Compile and flash tool for Seeed Studio XIAO ESP32C3 (sensor3-bt)

# Validate SENSOR_ID environment variable
if [ -z "$SENSOR_ID" ]; then
    echo "======================================================="
    echo "ERROR: SENSOR_ID environment variable is missing!"
    echo "======================================================="
    echo "You must specify the SENSOR_ID environment variable when calling this script."
    echo ""
    echo "Usage:"
    echo "  SENSOR_ID=<id> $0 [options] [port]"
    echo ""
    echo "Examples:"
    echo "  SENSOR_ID=veg_1 $0"
    echo "  SENSOR_ID=veg_2 $0 /dev/ttyACM1"
    echo "  SENSOR_ID=veg_3 $0 --compile-only"
    echo ""
    exit 1
fi

# Configuration
FQBN="esp32:esp32:XIAO_ESP32C3"
PORT="/dev/ttyACM1"
CLI_EXE="/app/arduino-ide/resources/app/lib/backend/resources/arduino-cli"
COMPILE_ONLY=false

# Simple argument parsing
for arg in "$@"; do
  case $arg in
    --compile-only|-c)
      COMPILE_ONLY=true
      shift
      ;;
    *)
      # If it's not a flag, assume it's the port
      if [[ -e "$arg" || "$arg" == /dev/* ]]; then
        PORT="$arg"
      fi
      ;;
  esac
done

# Dynamically generate Secrets.cpp using the environment variable
echo "Generating Secrets.cpp with SENSOR_ID=\"$SENSOR_ID\"..."
cat << EOF > Secrets.cpp
// Auto-generated by deploy.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')
// DO NOT EDIT MANUALLY - changes will be overwritten on deploy

#include "Secrets.h"

const char* SENSOR_ID = "${SENSOR_ID}";
EOF

echo "======================================================="
echo "STEP 1: Compiling for Seeed Studio XIAO ESP32C3..."
echo "======================================================="

# Run arduino-cli compile in Flatpak sandbox
flatpak run --command=sh cc.arduino.IDE2 -c "$CLI_EXE compile --fqbn $FQBN ."

if [ $? -eq 0 ]; then
    echo "SUCCESS: Compilation finished successfully."
    
    if [ "$COMPILE_ONLY" = true ]; then
        echo "Skipping upload as requested."
        exit 0
    fi

    echo ""
    echo "======================================================="
    echo "STEP 2: Uploading to board on port $PORT..."
    echo "======================================================="
    
    # Run arduino-cli upload in Flatpak sandbox
    flatpak run --command=sh cc.arduino.IDE2 -c "$CLI_EXE upload -p $PORT --fqbn $FQBN ."
    
    if [ $? -eq 0 ]; then
        echo "SUCCESS: Code uploaded to board successfully!"
        
        echo ""
        echo "======================================================="
        echo "STEP 3: Attaching to serial monitor on port $PORT..."
        echo "======================================================="
        echo "Automatically re-connecting when port is lost (deep sleep/reset)."
        echo "Press Ctrl+C to exit."
        echo ""
        
        # Set up a trap to exit the loop cleanly on Ctrl+C (SIGINT)
        trap "echo -e '\nExiting serial monitor...'; exit 0" SIGINT
        
        while true; do
            # Wait for the serial port device to become available
            if [ ! -e "$PORT" ]; then
                echo -n "Waiting for port $PORT to appear..."
                while [ ! -e "$PORT" ]; do
                    sleep 0.5
                    echo -n "."
                done
                echo " detected!"
                sleep 0.5 # Give the OS a moment to initialize the CDC port
            fi
            
            # Run arduino-cli monitor in Flatpak sandbox
            flatpak run --command=sh cc.arduino.IDE2 -c "$CLI_EXE monitor -p $PORT --config baudrate=115200"
            
            echo ""
            echo "Connection lost. Re-attaching as soon as $PORT becomes available..."
            sleep 1
        done
    else
        echo "FAILED: Upload failed. Check the port and ensure the device is in bootloader mode (hold BOOT, press RST)."
        exit 1
    fi
else
    echo "FAILED: Compilation errors encountered."
    exit 1
fi
